.webhosting_1: &webhosting_1
    hostname: webhosting_1.mycompany.com
    user: myuser
    account_root: /home/www/doc/myuser
    port: 22
    http_user: "{{user}}"
    configFile: ~/.ssh/config
    identityFile: ~/.ssh/id_rsa
    forwardAgent: true
    multiplexing: true
    sshOptions:
        UserKnownHostsFile: /dev/null
        StrictHostKeyChecking: no
    roles: app
    bin/php: /usr/local/php-8.1/bin/php -d memory_limit=-1
    bin/composer: "{{bin/php}} {{account_root}}/bin/composer2.phar"
    writable_mode: chmod
    composer_options: "{{composer_action}} --verbose --prefer-dist --no-progress --no-interaction --no-dev --optimize-autoloader --no-suggest --ignore-platform-req=ext-sodium"

myapp.mycompany.com:
    <<: *webhosting_1
    stage: production
    deploy_path: "{{account_root}}/mycompany.com/myapp"
    branch: master